DROP TABLE IF EXISTS events;

CREATE TABLE events (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  title VARCHAR(50) NOT NULL,
  event_description VARCHAR(256) NOT NULL,
  start TIMESTAMP,
  event_end TIMESTAMP,
  all_day BOOLEAN
);
